accounts/urls.py
"""Defines url patterens for accounts."""

from django.urls import path, include
from . import views

app_name = 'accounts'
urlpatterns = [
    #include default auth urls.
    path('', include('django.contrib.auth.urls')),
    #registration page.
    path('register/', views.register, name='register'),
]

learning_logs/urls.py
"""Defines the url patterns for learning_logs."""
from django.urls import path #needed when mapping urls to view.
from . import views

app_name = 'learning_logs'

#incudes the list of individual pages that can be requested from the learning_log app.
urlpatterns = [
    #home page.
    path('', views.index, name = 'index'),
    #page that shows all topics.
    path('topics/', views.topics, name='topics'),
    #detailed page for a single topic.
    path('topics/<int:topic_id>/', views.topic, name='topic'),
    #page for adding new topic.
    path('new_topic/', views.new_topic, name = 'new_topic'),
    #page for adding a new entry.
    path('new_entry/<int:topic_id>/', views.new_entry, name= 'new_entry'),
    #page for editing an entry.
    path('edit_entry/<int:entry_id>/', views.edit_entry, name= 'edit_entry'),
]

ll_project/urls.py
from django.contrib import admin #lets you use admin interface.
#include() for accessing the urls file in learning_logs folder.
from django.urls import path, include #path() used to map urls to view fns

#contains the urls from the apps in the project.
urlpatterns = [
    path('admin/', admin.site.urls), #all urls that can be requested from the admin site.
    path('accounts/', include('accounts.urls')),
    path('', include('learning_logs.urls')),
]

learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Topic(models.Model):
    """A topic the user is learning about."""
    text = models.CharField(max_length=200) #we use CharField when we want to store a small amt of text.
    date_added = models.DateTimeField(auto_now_add=True) #"auto_now_add=True": tells django to automatically set the current date and time whenever the user creates a new topic.
    owner = models.ForeignKey(User, on_delete=models.CASCADE) #if the user is deleted all the topics associated with that user will be deleted.

    def __str__(self):
        """Return the String represention of the model."""
        return self.text
    
class Entry(models.Model): #inherits from Model class.
    """Something specific learning about a topic."""
    #foreign key is the reference to the other records in the db. This is a code that connects each entry to a specific topic. 
    #each topic has been assigned a key or an id when its created.
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE) #"on_delete=models.CASCADE" if a topic is deleted, all the entries associated with that topic shoud be deleted.
    text = models.TextField() #for storing entries.
    date_added = models.DateTimeField(auto_now_add=True) #present the entries in the order they were created, and place the timestamp next to it.

    #nested class.
    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        """Return a simple string representing the entry."""
        if len(self.text) < 50:
            return f"{self.text}"
        else:
            return f"{self.text[:50]}..."  #how much info. will be shown representing each entry.

learning_logs/forms.py
from django import forms

from .models import Topic, Entry

class TopicForm(forms.ModelForm):
    class Meta:
        #we specify that that the form should be based on the Topic model.
        model = Topic
        fields = ['text'] #it should only inlude a text field.
        labels = {'text': ''} #the empty string i the labels dictionary tells django to not generate a label for the textfield.
        
class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text' : forms.Textarea(attrs= {'cols': 80})} #A widget is an HTML form element, such as a single-line text box, multiline text area, or dropdown list
        

learning_logs/views.py
from django.shortcuts import render, redirect
from .models import Topic, Entry
from .forms import TopicForm, EntryForm
from django.contrib.auth.decorators import login_required
from django.http import Http404

# Create your views here.
def index(request):
    """The homepage for learning_logs."""
    return render(request, 'learning_logs/index.html')

@login_required
def topics(request):
    """Show all topics."""
    #When a user is logged in, the request object has a request.user attribute set, which contains information about the user
    topics = Topic.objects.filter(owner = request.user).order_by('date_added')
    context = {'topics' : topics}
    return render(request, 'learning_logs/topics.html', context)

@login_required
def topic(request, topic_id):
    """Show a single topic and all it's entries."""
    topic = Topic.objects.get(id = topic_id)
    #Make sure the topic belongs to the current user.
    check_topic_owner(request, topic)
    """if topic.owner != request.user:
        raise Http404"""
    
    entries = topic.entry_set.order_by('-date_added') #-date_added: the minus sign sorts the result in reverse order, recently added first.
    context = {'topic': topic, 'entries': entries}
    return render(request, 'learning_logs/topic.html', context)

@login_required
def new_topic(request):
    """Add a new topic."""
    if request.method != 'POST':
        #No data submitted; create a blank form.
        form = TopicForm()  #we included no arguments when instantiating TopicForm, Django creates a blank form that the user can fill out.
    else:
        #POST data submitted; process data.
        form = TopicForm(data = request.POST) # pass it the data entered by the user, which is assigned to request.POST.
        if form.is_valid(): #The is_valid() method checks that all required fields have been filled in (all fields in a form are required by default) and that the data entered matches the field types expected
            new_topic = form.save(commit=False) #false because we have to modify the new topic before saving it to the database.
            new_topic.owner = request.user #set owner att to the current user.
            new_topic.save()
            return redirect('learning_logs:topics') #we'll redirect the user back to the topics page after they submit their topic.
        
    #Display a blank or invalid form.
    context =  {'form': form}
    return render(request, 'learning_logs/new_topic.html', context)

@login_required
def new_entry(request, topic_id):
    """Add a new entry for a perticular topic."""
    topic = Topic.objects.get(id = topic_id)
    check_topic_owner(request, topic)

    if request.method != 'POST':
        #No data submitted, create a blank form.
        form = EntryForm()
    else:
        #POST data submitted; process the data.
        form = EntryForm(request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return redirect('learning_logs:topic', topic_id = topic_id)
        
    #display a blank or invalid form.
    context  = {'topic': topic, 'form': form}
    return render(request, 'learning_logs/new_entry.html', context)

@login_required
def edit_entry(request, entry_id):
    """Edit an existing entry."""
    entry = Entry.objects.get(id = entry_id)
    topic = entry.topic
    check_topic_owner(request, topic)
    """if topic.owner != request.user:
        raise Http404"""

    if request.method != 'POST':
        #Initial request; pre-fill form with the current entry.
        form = EntryForm(instance=entry) #this arg tells djando to prefill the info from the existing entry object.
    else:
        #POST data submitted ; process data.
        form = EntryForm(instance=entry, data = request.POST)
        if form.is_valid():
            form.save()
            return redirect('learning_logs:topic', topic_id = topic.id)
        
    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'learning_logs/edit_entry.html', context)

def check_topic_owner(request, topic):
    if topic.owner != request.user:
        raise Http404

learning_logs/templates/learning_logs/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Learning Log</title>

  {% load django_bootstrap5 %}
  {% bootstrap_css %}
  {% bootstrap_javascript %}

</head>
<body>
  <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'learning_logs:index' %}">Learning Log</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
      data-bs-target="#navbarCollapse" aria-controls="navbar-Collapse" aria-expanded = "false" 
      aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav me-auto mb-2 mb-md-0">
          <li class="nav=item">
            <a class="nav-link" href="{% url 'learning_logs:topics' %}">
              Topics
            </a>
          </li>
        </ul> <!-- End of links on left side of navbar-->

        <!-- Account Related Links-->
         <ul class="navbar-nav ms-auto mb-2 mb-md-0">

          {% if user.is_authenticated %}
            <li class="nav-item">
              <span class="navbar-text me-2">Hello, {{ user.username }}.
              </span>
            </li>
          {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:register' %}">Register</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:login' %}">Log In</a>
            </li>
            {% endif %}

         </ul> <!-- End of account-related links -->

         {% if user.is_authenticated %}
          <form action="{% url 'accounts:logout' %}" method="post">
            {% csrf_token %}
            <button name="submit" class="btn btn-outline-secondary btn-sm">
              Log out </button>
          </form>
          {% endif %}
      </div> <!-- Closes collapsible parts of navbar -->

    </div> <!-- Closes navbar's container -->
  </nav> <!-- End of navbar -->

  <main class="container">
    <div class="pb-2 mb-2 border-bottom">
      {% block page_header  %}{% endblock page_header %}
    </div>
    <div>
      {% block content %} {% endblock content %}
    </div>
  </main>

</body>
</html>

learning_logs/templates/learning_logs/edit_entry.html
{% extends 'learning_logs/base.html' %}
{% load django_bootstrap5 %}

{% block page_header %}
<h2><a href="{% url 'learning_logs:topic' topic.id %}"><button class="btn btn-info btn-lg w-50">{{ topic }}</button></a></h2>
{% endblock page_header %}

{% block content %}
<h4>Edit Entry:</h4>
<form action="{% url 'learning_logs:edit_entry' entry.id %}" method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% bootstrap_button button_type="submit" content="Save chnages" %}
</form>

{% endblock content %}

learning_logs/templates/learning_logs/index.html
{% extends 'learning_logs/base.html' %}

{% block page_header %}
    <div class="p-3 mb-4 bg-light border-rounded-3">
        <div class="container-fluid py-4">
            <h1 class="display-3">Track Your Learning.</h1>       
            
            <p class="lead">Make your own Learning Log, and keep a list of topics you're learning about. 
                Whenever you learn something new about a topic, make an entry summarizing what you'ev  learned.</p>
            {% if user.is_authenticated %}
                <a class="btn btn-primary btn-lg mt-1" href="{% url 'learning_logs:topics' %}">Topics &raquo;</a>
            {% else %}
                <a class="btn btn-primary btn-lg mt-1" href="{% url 'accounts:register' %}">Register &raquo;</a>
            {% endif %}
        </div>
    </div>
{% endblock page_header %}

learning_logs/templates/learning_logs/new_entry.html
{% extends 'learning_logs/base.html' %}
{% load django_bootstrap5 %}

{% block page_header %}
<h2><a href="{% url 'learning_logs:topic' topic.id %}"><button class="btn btn-info btn-lg w-50">{{ topic }}</button></a></h2>
{% endblock page_header %}

{% block content %}
<h4>Add a new Entry:</h4>
<form action="{% url 'learning_logs:new_entry' topic.id %}" method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% bootstrap_button button_type="submit" content="Add Entry" %}
</form>

{% endblock content %}

learning_logs/templates/learning_logs/new_topic.html
{% extends "learning_logs/base.html" %}
{% load django_bootstrap5 %}

{% block page_header %}
<h2><a href="{% url 'learning_logs:topics' %}"><button class="btn btn-lg btn-outline-primary w-100">Topics</button></a></h2>
<h2><button class="btn btn-info btn-lg w-50">Add new Topic</button></h2>
{% endblock page_header %}

{% block content %}
    <!-- The action argument tells the browser where to send the data submitted in the form; in this case, we send it back to the view function new_topic().-->
    <form action="{% url 'learning_logs:new_topic' %}" method='post'>
        {% csrf_token %} <!-- to prevent attackers from using the form to gain unauthorized access to the server-->
        {% bootstrap_form form %}
        {% bootstrap_button button_type="submit" content="Add Topic" %}
    </form>

{% endblock content %}

learning_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html' %}
{% load django_bootstrap5 %}

{% block page_header %}
<h2><a href="{% url 'learning_logs:topics' %}"><button class="btn btn-lg btn-outline-primary w-100">Topics</button></a></h2>
<h1>Topic: {{ topic.text }}</h1>
{% endblock page_header %}

{% block content %}
<h6>
    <a href="{% url 'learning_logs:new_entry' topic.id %}">{% bootstrap_button button_type="submit" content="Add New Entry" %}</a>
</h6>

    {% for entry in entries %}
        <div class="card mb-3">
            <!-- Card heeader with timestamp and edit link -->
            <h4 class="card-header">
                {{ entry.date_added|date:'M d, Y H:i' }} <!-- a vertical line (|) represents a template filter—a function that modifies the value in a template variable during the rendering process.-->
                <small>
                    <a href="{% url 'learning_logs:edit_entry' entry.id %}"><button class="btn btn-outline-secondary">edit entry</button></a>
                </small>
            </h4>
            <!-- Card body with entry text. -->
            <div class="card-body">{{ entry.text|linebreaks }}</div> 
        </div>
    {% empty %}
        <p>There are no entries for this topic yet.</p>
    {% endfor %}

{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends 'learning_logs/base.html' %}
{% load django_bootstrap5 %}

{% block page_header %}
  <h1>Topics</h1>
{% endblock page_header %}

{% block content %}

<ul class="list-group border-bottom pb-2 mb-4"> 
    {% for topic in topics %} <!--loops through the list of topics from the context dictionary.-->
      <li class="list-group-item border-0">
        <a href="{% url 'learning_logs:topic' topic.id %}"><button class="btn btn-info btn-lg w-100">{{ topic.text }}</button></a> 
      </li>
    {% empty %} <!-- Tells django what to do where there are no items in the list. -->
      <li class="list-group-item border-1 pb-2 ">No topics have been added yet.</li>
    {% endfor %} <!--End of the loop-->
</ul>
<a href="{% url 'learning_logs:new_topic' %}">{% bootstrap_button button_type="submit" content="Add a new Topic" %}</a>

{% endblock content %}